services:
  frontend:
    image: ghcr.io/samay15jan/vpnlens-frontend:latest
    container_name: vpnlens-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: ghcr.io/samay15jan/vpnlens-backend:latest
    container_name: vpnlens-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - ./backend/data:/app/data
      - ./backend/keys/server2_key:/app/keys/server2_key:ro
    environment:
      NODE_ENV: production