services:
  frontend:
    image: ghcr.io/samay15jan/vpnlens-frontend:latest
    container_name: vpnlens-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: ghcr.io/samay15jan/vpnlens-backend:latest
    container_name: vpnlens-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - ./data/backend:/app/data
      - ./data/backend/keys/server2_key:/app/keys/server2_key:ro
    environment:
      NODE_ENV: production

  docs:
    image: ghcr.io/samay15jan/vpnlens-docs:latest
    container_name: vpnlens-docs
    restart: unless-stopped
    ports:
      - "3002:80"

  caddy:
    image: caddy:2.10.0-alpine
    container_name: vpnlens-caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./configs/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
    depends_on:
      - frontend
      - docs

  headscale:
    image: headscale/headscale:0.28.0
    container_name: vpnlens-headscale
    restart: unless-stopped
    command: serve
    labels:
      - "me.tale.headplane.target=headscale"
    volumes:
      - ./configs/headscale/config.yml:/etc/headscale/config.yaml:ro
      - ./data/headscale:/var/lib/headscale

  wireguard:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: vpnlens-wireguard
    restart: unless-stopped
    network_mode: host
    environment:
      - PORT=51821
      - WG_HOST=samay15jan.com
      - WG_DEFAULT_DNS=1.1.1.1
    volumes:
      - ./data/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

  headplane:
    image: ghcr.io/tale/headplane:latest
    container_name: vpnlens-headplane
    restart: unless-stopped
    ports:
      - "3003:3000"
    depends_on:
      - headscale
    volumes:
      - ./configs/headplane/config.yml:/etc/headplane/config.yaml:ro
      - ./data/headplane:/var/lib/headplane
      - ./configs/headscale/config.yml:/etc/headscale/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
