services:
  vpnlens-backend:
    build: .
    container_name: vpnlens-backend
    restart: unless-stopped

    ports:
      - "3001:3001"

    volumes:
      - ./data:/app/data

    environment:
      NODE_ENV: production
