services:
  vpnlens-backend:
    image: ghcr.io/samay15jan/vpnlens-backend:latest
    container_name: vpnlens-backend
    
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "3001:3001"

    volumes:
      - ./data:/app/data

    environment:
      NODE_ENV: production
