services:
  caddy:
    image: caddy:2.10.0-alpine
    container_name: caddy
    network_mode: host
    restart: unless-stopped

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - config:/config
      - data:/data

volumes:
  config:
  data:
