volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
    #  Optional:
    - PORT=51821
    #  - HOST=0.0.0.0
    - WG_HOST=samay15jan.com
    - WG_DEFAULT_DNS=1.1.1.1
    #  - INSECURE=false

    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    network_mode: host
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman

networks:
  caddy:
    external: true

